### PR TITLE
Parent Resolution Bug

### LINKED ISSUE #9: Parent Resolution Bug
If a parent is attempted to be extended in any form, either using a relative path or node_module path to a dry file it fails to resolve it and causes an overall silent command failure.

The issue appears to be the use of `require` at 
https://github.com/Cosium/dry-dry/blob/master/src/dry-package.ts#L108

It attempts to resolve at the global install location of `dry-dry` but the dependency was installed at the context of shell location that invoked the `dry` command. I can sort of work around it by locally installing `dry-dry` and executing something along the lines of `node path_to_dry-dry/index.js run someScriptName` but that is not going to work overall. 

Another issue exists too, if following the example dependencies declaration format:
```JSON
    "dependencies": {
      "parent": "1.0.0"
    }
```
`dry-dry` will attempt to execute the command `npm install --no-save 1.0.0`; it appears due to the conditional at https://github.com/Cosium/dry-dry/blob/master/src/dependency-resolver.ts#L23.

### PR DESCRIPTION
**Pull request by treilhes**
### Fix #9 

**Resolve dry dependencies relatively to the child module instead of dry-dry module.** 

To reproduce the bug:
1- install dry-dry globaly using "install dry-dry -g"
2- Take care to remove any "parent" from the global "node_modules" folder
3- Copy/paste the folder dist-test generated by the"dry inheritance" test into a folder without any folder "node_modules" in the folder hierarchy
4- open a shell/dos go into dist-test/parent and execute "dry pack"
5- In the shell go into dist-test/child and execute "dry pack"
The process will fail silently

The cause: 
The require function resolve dependencies in the folder hierarchy of dry-dry instead of child

Why test case works in dry-dry:
Because when resolving the "parent" dependency it installs the dependency in dry-dry/node_modules instead of dry-dry/dist-test/child/node_modules. dry-dry/node_modules is also part of dry-package.ts folder hierarchy so resolution is successfull

To fix the issue i've introduced a new package "import-cwd" that does the equivalent of require but starting from process.cwd. What do you think of this lib? is it ok or do you prefer a homemade solution?

**Fix indexOf test typo**

The test
` (dependencyVersion && dependencyVersion.indexOf(':') !== 1) ` is meant to handle two cases:

- A simple version number like "1.0.0"
- a file path like "file:../parent/parent-1.0.0.tgz"

Currently, the test check if the char ':' is at position 1 which doesn't make sense.
So the "simple version" is handled the same as "file path" which lead to `npm install --no-save 1.0.0`

The new test check if the char ':' exists in the string
` (dependencyVersion && dependencyVersion.indexOf(':') !== -1) `

### CODE REVIEW

**Comment by reda-alaoui** [comment]
@treilhes please fix the conflicts and we can merge it ;)

**Comment by treilhes** [comment]
@reda-alaoui Conflicts are fixed. :)

**Comment by reda-alaoui** [comment]
Something went wrong.
There are now 13 files modified in the PR (coming from the other PR), can you fix this?

**Comment by reda-alaoui** [comment]
Your previous PR came from your master.
I guess the branch of the current PR was created from your master which is unsynced.

**Comment by treilhes** [comment]
Ok, thanks for tip. I was scratching my head about what to do. thanks

**Comment by reda-alaoui** [comment]
Great, thank you :)

**Pull request merged**
